name: Basic CI pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: "Shibil Basith"

    steps:
      - name: Checkout code from GitHub repository
        uses: actions/checkout@v4

      - name: Print current working directory
        run: pwd

      - name: Print my name
        run: echo "My name is $NAME"

      - name: Print password
        run: echo "${{ secrets.PASSWORD }}"
